cengel:
  hibernate:
    entityScanPkgs: com.cengel.yyshop
  redis:
    domain: yyshop

pojo:
  #奇牛图片上传验证
  qiniu:
    accessKey: 9Mz3NWR91SmcuTr1mVvBW8Ha7SpSeLACA15OR0sm
    secretKey: 8ld8vCPfrQW1bkLHGzSnJOJxccLZjAE8z8XHxZSY
  # 系统默认常量
  base-context:
    ip: 47.98.169.89
    basePath: http://yyshop.com
    staticBase: http://47.98.169.89/static
    filesDir: D:/Documents/statics
  #发短信的配置参数
  msghelper:
    url: http://hprpt2.eucp.b2m.cn:8080/sdkproxy/sendsms.action
    key: 8SDK-EMY-6699-SBTOM
    password: 388474
    priority: 1
    suffixCode: 【智游宝】

#日志配置
logging:
  file: /application/springcloud/logs/${spring.application.name}.log
  level:
    root: info
    #org.springframework.cloud.sleuth: info   #目前用不到
    tk.mybatis: DEBUG
    com.weiare: DEBUG


spring:
  profiles: dev #开发环境
  cloud:
    zookeeper:
      connect-string: 192.168.200.158:2183
      discovery:
        register: true
      block-until-connected-wait: 100
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  #数据库配置
  datasource:
    name: test
    url: jdbc:mysql://47.98.169.89:3306/yy_shop?useUnicode=true&characterEncoding=UTF8
    username: yyshop
    password: Yy.Shop_2018
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 47.75.63.136
    port: 6379
    password: zhao
    timeout: 5000
    pool:
      max-active: 1024
      min-idle: 0 #最大空闲连接
      max-idle: 200 #最大空间连接
      max-wait: 1000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      testOnBorrow: true
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates
    suffix: .html
  #模板引擎
  freemarker:
    #关闭缓存
    cache: false
    #获得request
    request-context-attribute: ctx
    #模板加载的位置
    template-loader-path: classpath:/templates
    #前缀
    #suffix: .htm
    #后缀
    #prefix: /htm/
    #是否优先从文件系统加载模板以支持热加载，默认为true
    prefer-file-system-access: false
    settings:
      #          auto_import: /ui-all.ftl as ui
      number_format: 0.##
  #MQ配置
  rabbitmq:
    host: mq.yyshop.com   #rabbitMQ服务器地址
    port: 5672        #rabbitMQ服务器端口
    username: admin
    password: zc1992
    publisher-confirms: true
    virtual-host: /
  activemq:
    broker-url: tcp://192.168.200.159:61616
    packages:
      #            trust-all: true
      trusted: com.weiare,com.qianli.travel,java
    user: admin
    password: admin
    pool:
      #            expiry-timeou: 0
      idle-timeout: 5000
      max-connections: 10
  #mongodb
  data:
    mongodb:
      uri: mongodb://192.168.200.159:27017/weiare
  cache:
    redis:
      key-prefix: shop_cache_
      time-to-live: 24*3600 #秒

management:
  endpoint:
    dubbo-configs:
      enabled: true
    dubbo:
      enabled: true
    dubbo-services:
      enabled: true
    dubbo-properties:
      enabled: true
    dubbo-shutdown:
      enabled: true
    dubbo-references:
      enabled: true
  health:
    dubbo:
      status:
        defaults: memory
        extras: load,threadpool
  endpoints:
    web:
      exposure:
        include: '*'

